name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Test
        run: make test
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38
